# Generated by Django 4.2.11 on 2024-06-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SensorData_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("battery_level", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_25", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_50", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_75", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "electrical_conductivity",
                    models.DecimalField(decimal_places=1, max_digits=2),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.sensor_2"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SensorData_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("battery_level", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_25", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_50", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_75", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "electrical_conductivity",
                    models.DecimalField(decimal_places=1, max_digits=2),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.sensor_1"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
