# Generated by Django 5.0.6 on 2024-06-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sensor_1_sensor_2_sensordata_2_sensordata_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor_1',
        ),
        migrations.DeleteModel(
            name='Sensor_2',
        ),
        migrations.RemoveField(
            model_name='sensordata_1',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensordata_2',
            name='sensor',
        ),
    ]
