# Generated by Django 5.0.6 on 2024-07-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_sensor_1_delete_sensor_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='sensordata_1',
            name='battery_level',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_1',
            name='electrical_conductivity',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_1',
            name='humidity_25',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_1',
            name='humidity_50',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_1',
            name='humidity_75',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_2',
            name='battery_level',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_2',
            name='electrical_conductivity',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_2',
            name='humidity_25',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_2',
            name='humidity_50',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sensordata_2',
            name='humidity_75',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
    ]
